# ==========================================================
# Night Core — Safe Run & Signed Push Script
# Maintainer: xnfinite
# Purpose: Verify AUFS, sign, and safely push verified commits
# ==========================================================

Write-Host "
🚀 Starting Night Core Safe Run (Signed Mode)" -ForegroundColor Cyan
Set-Location (Split-Path -Parent \System.Management.Automation.InvocationInfo.MyCommand.Path)

# === Step 1: Ensure release policy exists ===
if (-not (Test-Path 'docs/internal/RELEASE_POLICY.md')) {
    Write-Host '⚠️  RELEASE_POLICY.md not found — creating default policy...' -ForegroundColor Yellow
    New-Item -ItemType Directory -Force -Path docs/internal | Out-Null
    Set-Content docs/internal/RELEASE_POLICY.md '# Night Core — Internal Release Policy (Auto-Generated by Safe Run)'
}

# === Step 2: Build and verify project ===
Write-Host "
🔧 Building Night Core..." -ForegroundColor Cyan
cargo build
if (\64 -ne 0) { Write-Host '❌ Build failed, aborting.' -ForegroundColor Red; exit 1 }

Write-Host "
🧩 Running AUFS verification..." -ForegroundColor Cyan
cargo run -- upgrade --manifest upgrades/manifests/upgrade_manifest.json
if (\64 -ne 0) { Write-Host '❌ AUFS verification failed, aborting.' -ForegroundColor Red; exit 1 }

# === Step 3: Safe file allowlist check ===
\ = @(
  'baseline.json',
  'logs/audit.log',
  'logs/orchestration_report.json',
  'upgrades/manifests/upgrade_manifest.json',
  'upgrades/signatures',
  'keys/maintainers',
  'scripts',
  'docs/NOTICE.html',
  'README_NOTICE.txt',
  'docs/internal/RELEASE_POLICY.md'
)

Write-Host "
🧠 Checking modified files..." -ForegroundColor Cyan
\ = git status --porcelain | ForEach-Object { \.Trim() -split '\s+' | Select-Object -Last 1 }
foreach (\README_NOTICE.txt in \) {
    if (-not (\ | Where-Object { \README_NOTICE.txt -like "\*" })) {
        Write-Host "❌ Unsafe file detected: \README_NOTICE.txt" -ForegroundColor Red
        Write-Host "Push blocked. File not in allowlist." -ForegroundColor Red
        exit 1
    }
}

# === Step 4: Signed commit ===
Write-Host "
📝 Creating signed commit..." -ForegroundColor Cyan
git add -A
git commit -S -m '🔒 Safe Signed Commit — Verified AUFS Chain (xnfinite)'
if (\64 -ne 0) { Write-Host '⚠️  No changes to commit or signing failed.' -ForegroundColor Yellow }

# === Step 5: Push to main ===
Write-Host "
🌐 Pushing to origin/main..." -ForegroundColor Cyan
git push origin main
if (\64 -ne 0) { Write-Host '❌ Push failed.' -ForegroundColor Red; exit 1 }

Write-Host "
✅ Safe signed run completed successfully!" -ForegroundColor Green
